//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Autor
{
    public Autor()
    {
        this.Table_Livro = new HashSet<Livro>();
    }

    public int ID_Autor { get; set; }
    public string Nome { get; set; }
    public string Apelido { get; set; }

    public virtual ICollection<Livro> Table_Livro { get; set; }
}

public partial class Categoria
{
    public Categoria()
    {
        this.Table_Livro = new HashSet<Livro>();
    }

    public int ID_Categoria { get; set; }
    public string Nome_Categoria { get; set; }

    public virtual ICollection<Livro> Table_Livro { get; set; }
}

public partial class Editora
{
    public Editora()
    {
        this.Table_Livro = new HashSet<Livro>();
    }

    public int ID_Editora { get; set; }
    public string Nome { get; set; }
    public string Descricao { get; set; }

    public virtual ICollection<Livro> Table_Livro { get; set; }
}

public partial class Livro
{
    public Livro()
    {
        this.Table_UtilizadorLivro = new HashSet<UtilizadorLivro>();
    }

    public int ID_Livro { get; set; }
    public string ISBN { get; set; }
    public string Titulo { get; set; }
    public Nullable<System.DateTime> Data_Publicacao { get; set; }
    public int Categoria { get; set; }
    public int Editora { get; set; }
    public Nullable<int> Autor { get; set; }
    public string Descricao { get; set; }

    public virtual Autor Table_Autor { get; set; }
    public virtual Categoria Table_Categoria { get; set; }
    public virtual Editora Table_Editora { get; set; }
    public virtual ICollection<UtilizadorLivro> Table_UtilizadorLivro { get; set; }
}

public partial class Utilizador
{
    public Utilizador()
    {
        this.Table_UtilizadorLivro = new HashSet<UtilizadorLivro>();
    }

    public int ID_Utilizador { get; set; }
    public string Nome { get; set; }
    public string Apelido { get; set; }
    public string NumeroContato { get; set; }
    public string Email { get; set; }
    public string EnderecoMorada { get; set; }
    public string NomeUtilizador { get; set; }

    public virtual ICollection<UtilizadorLivro> Table_UtilizadorLivro { get; set; }
}

public partial class UtilizadorLivro
{
    public int ID_Utilizador { get; set; }
    public int ID_Livro { get; set; }
    public System.DateTime dataEmprestimo { get; set; }
    public System.DateTime dateDevolucao { get; set; }

    public virtual Livro Table_Livro { get; set; }
    public virtual Utilizador Table_Utilizador { get; set; }
}

public partial class View_Livro
{
    public int Código { get; set; }
    public string ISBN { get; set; }
    public string Titulo { get; set; }
    public Nullable<System.DateTime> Data_publicação { get; set; }
    public string Nome_Categoria { get; set; }
    public string Editora { get; set; }
    public string Autor { get; set; }
    public string Descrição { get; set; }
}

public partial class view_utilizador_req_livro
{
    public string Nome { get; set; }
    public string IDLogin { get; set; }
    public string Titulo { get; set; }
    public string Autor { get; set; }
    public string Editora { get; set; }
    public System.DateTime dataEmprestimo { get; set; }
    public System.DateTime dateDevolucao { get; set; }
    public string Descricao { get; set; }
}
